export const AuthConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',
  LOGOUT: 'LOGOUT',
  CHECK_AUTO_LOGOUT: 'CHECK_AUTO_LOGOUT',
};

export const BrandConstants = {
  GET_BRAND_BY_CLAIM_REQUEST: 'GET_BRAND_BY_CLAIM_REQUEST',
  GET_BRAND_BY_CLAIM_SUCCESS: 'GET_BRAND_BY_CLAIM_SUCCESS',
  GET_BRAND_BY_CLAIM_FAILURE: 'GET_BRAND_BY_CLAIM_FAILURE',

  GET_BRAND_BY_ID_REQUEST: 'GET_BRAND_BY_ID_REQUEST',
  GET_BRAND_BY_ID_SUCCESS: 'GET_BRAND_BY_ID_SUCCESS',
  GET_BRAND_BY_ID_FAILURE: 'GET_BRAND_BY_ID_FAILURE',

  GET_BALANCE_REQUEST: 'GET_BALANCE_REQUEST',
  GET_BALANCE_SUCCESS: 'GET_BALANCE_SUCCESS',
  GET_BALANCE_FAILURE: 'GET_BALANCE_FAILURE',

  GET_INVOICES_REQUEST: 'GET_INVOICES_REQUEST',
  GET_INVOICES_SUCCESS: 'GET_INVOICES_SUCCESS',
  GET_INVOICES_FAILURE: 'GET_INVOICES_FAILURE',
};

export const StoreConstants = {
  ADD_STORE_REQUEST: 'ADD_STORE_REQUEST',
  ADD_STORE_SUCCESS: 'ADD_STORE_SUCCESS',
  ADD_STORE_FAILURE: 'ADD_STORE_FAILURE',

  GET_STORE_LIST_REQUEST: 'GET_STORE_LIST_REQUEST',
  GET_STORE_LIST_SUCCESS: 'GET_STORE_LIST_SUCCESS',
  GET_STORE_LIST_FAILURE: 'GET_STORE_LIST_FAILURE',

  DELETE_STORE_REQUEST: 'DELETE_STORE_REQUEST',
  DELETE_STORE_SUCCESS: 'DELETE_STORE_SUCCESS',
  DELETE_STORE_FAILURE: 'DELETE_STORE_FAILURE',

  GET_STORE_BONUS_REQUEST: 'GET_STORE_BONUS_REQUEST',
  GET_STORE_BONUS_SUCCESS: 'GET_STORE_BONUS_SUCCESS',
  GET_STORE_BONUS_FAILURE: 'GET_STORE_BONUS_FAILURE',

  DOWNLOAD_STORES_REQUEST: 'DOWNLOAD_STORES_REQUEST',
  DOWNLOAD_STORES_SUCCESS: 'DOWNLOAD_STORES_SUCCESS',
  DOWNLOAD_STORES_FAILURE: 'DOWNLOAD_STORES_FAILURE',

  ADD_EMPLOYEE_TO_STORE_REQUEST: 'ADD_EMPLOYEE_TO_STORE_REQUEST',
  ADD_EMPLOYEE_TO_STORE_SUCCESS: 'ADD_EMPLOYEE_TO_STORE_SUCCESS',
  ADD_EMPLOYEE_TO_STORE_FAILURE: 'ADD_EMPLOYEE_TO_STORE_FAILURE',
};

export const EmployeeConstants = {
  GET_EMPLOYEE_BY_ID_REQUEST: 'GET_EMPLOYEE_BY_ID_REQUEST',
  GET_EMPLOYEE_BY_ID_SUCCESS: 'GET_EMPLOYEE_BY_ID_SUCCESS',
  GET_EMPLOYEE_BY_ID_FAILURE: 'GET_EMPLOYEE_BY_ID_FAILURE',

  GET_EMPLOYEES_REQUEST: 'GET_EMPLOYEES_REQUEST',
  GET_EMPLOYEES_SUCCESS: 'GET_EMPLOYEES_SUCCESS',
  GET_EMPLOYEES_FAILURE: 'GET_EMPLOYEES_FAILURE',

  TOGGLE_EMPLOYEE_STATUS_REQUEST: 'TOGGLE_EMPLOYEE_STATUS_REQUEST',
  TOGGLE_EMPLOYEE_STATUS_SUCCESS: 'TOGGLE_EMPLOYEE_STATUS_SUCCESS',
  TOGGLE_EMPLOYEE_STATUS_FAILURE: 'TOGGLE_EMPLOYEE_STATUS_FAILURE',

  ADD_EMPLOYEE_REQUEST: 'ADD_EMPLOYEE_REQUEST',
  ADD_EMPLOYEE_SUCCESS: 'ADD_EMPLOYEE_SUCCESS',
  ADD_EMPLOYEE_FAILURE: 'ADD_EMPLOYEE_FAILURE',

  GET_EMPLOYEE_BONUSES_REQUEST: 'GET_EMPLOYEE_BONUSES_REQUEST',
  GET_EMPLOYEE_BONUSES_SUCCESS: 'GET_EMPLOYEE_BONUSES_SUCCESS',
  GET_EMPLOYEE_BONUSES_FAILURE: 'GET_EMPLOYEE_BONUSES_FAILURE',

  DOWNLOAD_EMPLOYEES_REQUEST: 'DOWNLOAD_EMPLOYEES_REQUEST',
  DOWNLOAD_EMPLOYEES_SUCCESS: 'DOWNLOAD_EMPLOYEES_SUCCESS',
  DOWNLOAD_EMPLOYEES_FAILURE: 'DOWNLOAD_EMPLOYEES_FAILURE',
};

export const VoucherConstants = {
  GET_VOUCHERS_REQUEST: 'GET_VOUCHERS_REQUEST',
  GET_VOUCHERS_SUCCESS: 'GET_VOUCHERS_SUCCESS',
  GET_VOUCHERS_FAILURE: 'GET_VOUCHERS_FAILURE',

  GET_VOUCHER_BY_ID_REQUEST: 'GET_VOUCHER_BY_ID_REQUEST',
  GET_VOUCHER_BY_ID_SUCCESS: 'GET_VOUCHER_BY_ID_SUCCESS',
  GET_VOUCHER_BY_ID_FAILURE: 'GET_VOUCHER_BY_ID_FAILURE',

  DELETE_VOUCHER_REQUEST: 'DELETE_VOUCHER_REQUEST',
  DELETE_VOUCHER_SUCCESS: 'DELETE_VOUCHER_SUCCESS',
  DELETE_VOUCHER_FAILURE: 'DELETE_VOUCHER_FAILURE',

  GET_REDEMPTION_REQUEST: 'GET_REDEMPTION_REQUEST',
  GET_REDEMPTION_SUCCESS: 'GET_REDEMPTION_SUCCESS',
  GET_REDEMPTION_FAILURE: 'GET_REDEMPTION_FAILURE',

  ADD_VOUCHER_REQUEST: 'ADD_VOUCHER_REQUEST',
  ADD_VOUCHER_SUCCESS: 'ADD_VOUCHER_SUCCESS',
  ADD_VOUCHER_FAILURE: 'ADD_VOUCHER_FAILURE',

  DOWNLOAD_VOUCHERS_REQUEST: 'DOWNLOAD_VOUCHERS_REQUEST',
  DOWNLOAD_VOUCHERS_SUCCESS: 'DOWNLOAD_VOUCHERS_SUCCESS',
  DOWNLOAD_VOUCHERS_FAILURE: 'DOWNLOAD_VOUCHERS_FAILURE',
};

export const RuleConstants = {
  GET_RULES_REQUEST: 'GET_RULES_REQUEST',
  GET_RULES_SUCCESS: 'GET_RULES_SUCCESS',
  GET_RULES_FAILURE: 'GET_RULES_FAILURE',
};

export const InvoiceConstants = {
  DOWNLOAD_INVOICES_REQUEST: 'DOWNLOAD_INVOICES_REQUEST',
  DOWNLOAD_INVOICES_SUCCESS: 'DOWNLOAD_INVOICES_SUCCESS',
  DOWNLOAD_INVOICES_FAILURE: 'DOWNLOAD_INVOICES_FAILURE',
};
